DROP TABLE IF EXISTS device_service;
DROP TABLE IF EXISTS device;
DROP TABLE IF EXISTS service;

CREATE TABLE device (
    id bigint GENERATED BY DEFAULT AS IDENTITY,
    customer_id bigint,
    system_name varchar(255),
    type varchar(255),
    PRIMARY KEY (id),
    UNIQUE (system_name, type, customer_id)
);

CREATE TABLE service (
    id bigint GENERATED BY DEFAULT AS IDENTITY,
    name varchar(255) UNIQUE,
    price float(24),
    PRIMARY KEY (id)
);

CREATE TABLE device_service (
    device_id bigint NOT NULL,
    service_id bigint NOT NULL,
    PRIMARY KEY (device_id, service_id),
    FOREIGN KEY (service_id) REFERENCES service(id) ON DELETE CASCADE,
    FOREIGN KEY (device_id) REFERENCES device(id) ON DELETE CASCADE
);